### ISSUE TITLE
Debian_Version initialized instead of Upstream_Version

### ISSUE THREAD

**Issue by teselkin** [agx/git-buildpackage#20]
changelog.py [1] initializes Debian_Version property if there is no hyphen found in version string, but that's wrong. According to Debian policy [2], Debian_Version is the part *after* hyphen, and if there is no hyphen then there is no Debian version.

[1] https://github.com/agx/git-buildpackage/blob/master/gbp/deb/changelog.py#L113
[2] https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-Version

**Comment by agx** [comment]
In case of a native package (no hyphen) the Debian Version number is the only version number available
